module archive

import os

// ======================================================================
// Unit tests — pure .PKGINFO text parsing (no real archive needed)
// ======================================================================

fn test_parse_pkginfo_basic() {
	data := 'pkgname = testpkg\npkgver = 1.0-1\npkgdesc = Test description\nurl = https://example.com\narch = any\nbuilddate = 1234567890\npackager = Test User <test@example.com>\nsize = 987654\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)

	assert pkg.name == 'testpkg'
	assert pkg.name_hash == compute_name_hash('testpkg')
	assert pkg.version == '1.0-1'
	assert pkg.desc == 'Test description'
	assert pkg.url == 'https://example.com'
	assert pkg.arch == 'any'
	assert pkg.build_date == 1234567890
	assert pkg.packager == 'Test User <test@example.com>'
	assert pkg.isize == 987654
}

fn test_parse_pkginfo_multivalue_fields() {
	data := 'pkgname = multi-pkg\npkgver = 2.0\nlicense = MIT\nlicense = Apache-2.0\ndepend = libfoo>=1.0\ndepend = libbar\ndepend = libbaz<3.0\nprovides = virtual-foo\nconflict = old-foo\nreplaces = legacy-foo\nbackup = /etc/foo.conf\nbackup = /etc/foo/bar.conf\ngroup = foo-group\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)

	assert pkg.name == 'multi-pkg'

	// Licenses accumulate
	assert pkg.licenses.len == 2
	assert 'MIT' in pkg.licenses
	assert 'Apache-2.0' in pkg.licenses

	// Dependencies
	assert pkg.depends.len == 3
	mut found_libfoo := false
	mut found_libbar := false
	mut found_libbaz := false
	for dep in pkg.depends {
		if dep.name == 'libfoo' {
			found_libfoo = true
			assert dep.version == '1.0'
			assert dep.modifier == .ge
		}
		if dep.name == 'libbar' {
			found_libbar = true
			assert dep.version == ''
			assert dep.modifier == .any
		}
		if dep.name == 'libbaz' {
			found_libbaz = true
			assert dep.version == '3.0'
			assert dep.modifier == .lt
		}
	}
	assert found_libfoo
	assert found_libbar
	assert found_libbaz

	// Provides / conflicts / replaces
	assert pkg.provides.len == 1
	assert pkg.provides[0].name == 'virtual-foo'
	assert pkg.conflicts.len == 1
	assert pkg.conflicts[0].name == 'old-foo'
	assert pkg.replaces.len == 1
	assert pkg.replaces[0].name == 'legacy-foo'

	// Backup files
	assert pkg.backup.len == 2
	assert pkg.backup[0].name == '/etc/foo.conf'
	assert pkg.backup[1].name == '/etc/foo/bar.conf'

	// Groups
	assert pkg.groups.len == 1
	assert pkg.groups[0] == 'foo-group'
}

fn test_parse_pkginfo_with_comments_and_blanks() {
	data := '# Generated by makepkg\n# some comment\n\npkgname = comment-pkg\n\npkgver = 1.0\n\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)

	assert pkg.name == 'comment-pkg'
	assert pkg.version == '1.0'
}

fn test_parse_pkginfo_optdepend() {
	data := 'pkgname = opt-test\npkgver = 1.0\noptdepend = gd: for memusagestat\noptdepend = perl: for mtrace\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)

	assert pkg.optdepends.len == 2
	assert pkg.optdepends[0].name == 'gd'
	assert pkg.optdepends[1].name == 'perl'
}

fn test_parse_pkginfo_empty_data() {
	mut pkg := Package{}
	parse_pkginfo([], mut pkg)
	assert pkg.name == ''
}

fn test_parse_pkginfo_provides_with_eq() {
	// Format: provides = libacl.so=1-64
	data := 'pkgname = libacl-test\npkgver = 1.0\nprovides = libacl.so=1-64\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)

	assert pkg.provides.len == 1
	assert pkg.provides[0].name == 'libacl.so'
	assert pkg.provides[0].version == '1-64'
	assert pkg.provides[0].modifier == .eq
}

fn test_parse_pkginfo_provides_without_version() {
	data := 'pkgname = virtual-test\npkgver = 1.0\nprovides = virtual-pkg\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)

	assert pkg.provides.len == 1
	assert pkg.provides[0].name == 'virtual-pkg'
	assert pkg.provides[0].version == ''
	assert pkg.provides[0].modifier == .any
}

fn test_parse_pkginfo_xdata_is_ignored() {
	// xdata is not currently parsed by archive reader
	data := 'pkgname = xdata-pkg\npkgver = 1.0\nxdata = pkgtype=split\n'
	mut pkg := Package{}
	parse_pkginfo(data.bytes(), mut pkg)
	assert pkg.name == 'xdata-pkg'
	assert pkg.version == '1.0'
	// xdata should not error or affect other fields
}

// ======================================================================
// Integration tests — real .pkg.tar.zst files
// ======================================================================

const glibc_path = '/var/cache/pacman/pkg/glibc-2.43+r22+g8362e8ce10b2-4-x86_64_v3.pkg.tar.zst'

const acl_path = '/var/cache/pacman/pkg/acl-2.3.2-2.1-x86_64_v3.pkg.tar.zst'

fn check_pkg_skipped(path string) bool {
	if !os.exists(path) {
		return true
	}
	// Also skip if we don't have permissions
	if !os.is_file(path) {
		return true
	}
	return false
}

fn test_load_pkg_metadata_glibc() {
	if check_pkg_skipped(glibc_path) {
		return
	}
	pkg := load_pkg_metadata(glibc_path) or {
		assert false, 'load_pkg_metadata(glibc) failed: ${err}'
		return
	}

	assert pkg.name == 'glibc'
	assert pkg.version == '2.43+r22+g8362e8ce10b2-4'
	assert pkg.desc == 'GNU C Library'
	assert pkg.url == 'https://www.gnu.org/software/libc'
	assert pkg.arch == 'x86_64_v3'
	assert pkg.packager == 'CachyOS <admin@cachyos.org>'
	assert pkg.build_date == 1777750710
	assert pkg.isize == 53144214
	assert pkg.base == 'glibc'

	// Licenses
	assert pkg.licenses.len == 2
	assert 'GPL-2.0-or-later' in pkg.licenses
	assert 'LGPL-2.1-or-later' in pkg.licenses

	// Dependencies
	assert pkg.depends.len >= 3
	mut found_dep := map[string]bool{}
	for dep in pkg.depends {
		found_dep[dep.name] = true
	}
	assert found_dep['linux-api-headers'] or { false }
	assert found_dep['tzdata'] or { false }
	assert found_dep['filesystem'] or { false }

	// Check versioned dependency
	for dep in pkg.depends {
		if dep.name == 'linux-api-headers' {
			assert dep.version == '4.10'
			assert dep.modifier == .ge
			break
		}
	}

	// Optional dependencies
	assert pkg.optdepends.len >= 2
	mut found_opt := map[string]bool{}
	for dep in pkg.optdepends {
		found_opt[dep.name] = true
	}
	assert found_opt['gd'] or { false }
	assert found_opt['perl'] or { false }

	// Origin should be file
	assert pkg.origin == PackageOrigin.file

	// Scriptlet should NOT be set by metadata-only load
	assert pkg.scriptlet == false
}

fn test_load_pkg_metadata_acl() {
	if check_pkg_skipped(acl_path) {
		return
	}
	pkg := load_pkg_metadata(acl_path) or {
		assert false, 'load_pkg_metadata(acl) failed: ${err}'
		return
	}

	assert pkg.name == 'acl'
	assert pkg.version == '2.3.2-2.1'
	assert pkg.desc == 'Access control list utilities, libraries and headers'
	assert pkg.url == 'https://savannah.nongnu.org/projects/acl'
	assert pkg.arch == 'x86_64_v3'
	assert pkg.packager == 'CachyOS <admin@cachyos.org>'
	assert pkg.build_date == 1776177186
	assert pkg.isize == 346398

	// Provides
	assert pkg.provides.len == 1
	assert pkg.provides[0].name == 'libacl.so'
	assert pkg.provides[0].version == '1-64'
	assert pkg.provides[0].modifier == .eq

	// Dependencies
	assert pkg.depends.len == 1
	assert pkg.depends[0].name == 'glibc'
}

fn test_load_pkg_full_glibc() {
	if check_pkg_skipped(glibc_path) {
		return
	}
	pkg := load_pkg_full(glibc_path) or {
		assert false, 'load_pkg_full(glibc) failed: ${err}'
		return
	}

	// Metadata
	assert pkg.name == 'glibc'
	assert pkg.version == '2.43+r22+g8362e8ce10b2-4'

	// Scriptlet detection (.INSTALL present)
	assert pkg.scriptlet == true

	// File list should have entries
	assert pkg.files.files.len > 0

	// Should include known files and dirs
	mut found_etc := false
	for f in pkg.files.files {
		if f.name == 'etc/' {
			found_etc = true
			break
		}
	}
	assert found_etc, 'expected "etc/" in file list'
}

fn test_load_pkg_full_acl() {
	if check_pkg_skipped(acl_path) {
		return
	}
	pkg := load_pkg_full(acl_path) or {
		assert false, 'load_pkg_full(acl) failed: ${err}'
		return
	}

	// Metadata
	assert pkg.name == 'acl'

	// No .INSTALL in acl
	assert pkg.scriptlet == false

	// acl has ~102 total entries: .BUILDINFO, .MTREE, .PKGINFO + ~99 files/dirs
	assert pkg.files.files.len > 90

	// Verify specific files exist
	mut files_found := map[string]bool{}
	for f in pkg.files.files {
		files_found[f.name] = true
	}
	assert files_found['usr/bin/chacl'] or { false }
	assert files_found['usr/bin/getfacl'] or { false }
	assert files_found['usr/bin/setfacl'] or { false }
	assert files_found['usr/include/acl/libacl.h'] or { false }
	assert files_found['usr/lib/libacl.so.1.1.2302'] or { false }

	// Symlinks
	assert files_found['usr/lib/libacl.so'] or { false }
	assert files_found['usr/lib/libacl.so.1'] or { false }
}

// ======================================================================
// Edge cases
// ======================================================================

fn test_load_pkg_metadata_nonexistent_file() {
	pkg := load_pkg_metadata('/nonexistent/pkg.tar.zst') or {
		// Expected error
		return
	}
	assert false, 'expected error for nonexistent file'
}

fn test_load_pkg_metadata_not_an_archive() {
	tmp_path := '/tmp/ace-test-not-an-archive'
	os.write_file(tmp_path, 'this is not an archive') or {
		assert false, 'failed to write test file'
		return
	}
	defer {
		os.rm(tmp_path) or {}
	}

	pkg := load_pkg_metadata(tmp_path) or {
		// Expected error — file is not a valid archive
		return
	}
	assert false, 'expected error for non-archive file'
}
