// gen_pkg_tar_zst — generates minimal .pkg.tar.zst fixture files.
//
// Output: tests/fixtures/output/*.pkg.tar.zst
// Requires: tar and zstd CLI tools.

import os

const output_dir = 'tests/fixtures/output'

__global (
	pkg_temp_counter int
)

fn ensure_output_dir() {
	os.mkdir_all(output_dir, os.MkdirParams{}) or { panic('mkdir: ${err}') }
}

fn gen_temp_dir() string {
	pkg_temp_counter++
	dir := os.join_path(os.temp_dir(), 'ace-fixture-pkg-${pkg_temp_counter}')
	os.mkdir_all(dir, os.MkdirParams{}) or { panic('mkdir: ${err}') }
	return dir
}

fn write_file(path string, content string) {
	os.mkdir_all(os.dir(path), os.MkdirParams{}) or { panic('mkdir: ${err}') }
	os.write_file(path, content) or { panic('write: ${err}') }
}

fn pack_pkg(tmpdir string, pkgname string) {
	out_zst := os.join_path(output_dir, '${pkgname}.pkg.tar.zst')
	// Use tar to create a POSIX archive, pipe through zstd
	res := os.execute('tar --format=posix -cf - -C "${tmpdir}" . | zstd -f -q -o "${out_zst}"')
	if res.exit_code != 0 {
		eprintln('pack failed: ${res.output}')
	}
}

fn build_hello_pkg() {
	td := gen_temp_dir()
	defer { os.rmdir_all(td) or {} }

	write_file('${td}/.PKGINFO', '# Generated by ace fixture generator
pkgname = hello
pkgbase = hello
pkgver = 1.0-1
pkgdesc = A friendly greeting program
url = https://example.com/hello
builddate = 1700000000
packager = Fixture Builder <test@ace.local>
size = 4096
arch = x86_64
license = GPL
depend = glibc>=2.35
')
	write_file('${td}/usr/bin/hello', '#!/bin/sh\necho "Hello, world!"\n')
	os.chmod('${td}/usr/bin/hello', 0o755) or {}
	write_file('${td}/usr/share/man/man1/hello.1', '.TH HELLO 1 "January 2024"\n.SH NAME\nhello - friendly greeting\n')
	pack_pkg(td, 'hello-1.0-1-x86_64')
	println('  wrote ${output_dir}/hello-1.0-1-x86_64.pkg.tar.zst')
}

fn build_libfoo_pkg() {
	td := gen_temp_dir()
	defer { os.rmdir_all(td) or {} }

	write_file('${td}/.PKGINFO', '# Generated by ace fixture generator
pkgname = libfoo
pkgbase = libfoo
pkgver = 2.1-3
pkgdesc = An example library
url = https://example.com/libfoo
builddate = 1700000100
packager = Fixture Builder <test@ace.local>
size = 2048
arch = x86_64
license = LGPL
depend = hello
optdepend = docs: for documentation
provides = libfoo.so=2
')
	write_file('${td}/usr/lib/libfoo.so', '')
	write_file('${td}/usr/lib/libfoo.so.2', '')
	write_file('${td}/usr/lib/libfoo.so.2.1.3', '')
	write_file('${td}/usr/include/foo.h', '#ifndef FOO_H\n#define FOO_H\nvoid foo(void);\n#endif\n')
	pack_pkg(td, 'libfoo-2.1-3-x86_64')
	println('  wrote ${output_dir}/libfoo-2.1-3-x86_64.pkg.tar.zst')
}

fn build_epoch_pkg() {
	td := gen_temp_dir()
	defer { os.rmdir_all(td) or {} }

	write_file('${td}/.PKGINFO', '# Generated by ace fixture generator
pkgname = epoch
pkgbase = epoch
pkgver = 2:1.0-1
pkgdesc = Package with epoch 2
url = https://example.com/epoch
builddate = 1700000200
packager = Fixture Builder <test@ace.local>
size = 1024
arch = any
license = MIT
')
	write_file('${td}/usr/bin/epoch', '#!/bin/sh\necho "epoch:$EPOCH"\n')
	os.chmod('${td}/usr/bin/epoch', 0o755) or {}
	pack_pkg(td, 'epoch-2:1.0-1-any')
	println('  wrote ${output_dir}/epoch-2:1.0-1-any.pkg.tar.zst')
}

fn build_scriptlet_pkg() {
	td := gen_temp_dir()
	defer { os.rmdir_all(td) or {} }

	write_file('${td}/.PKGINFO', '# Generated by ace fixture generator
pkgname = scriptlet
pkgbase = scriptlet
pkgver = 1.0-1
pkgdesc = Package with install scriptlet
url = https://example.com/scriptlet
builddate = 1700000300
packager = Fixture Builder <test@ace.local>
size = 512
arch = x86_64
license = GPL
depend = glibc>=2.35
')
	write_file('${td}/.INSTALL', 'post_install() {\n    echo "Installed!"\n}\n\npost_upgrade() {\n    echo "Upgraded!"\n}\n\npost_remove() {\n    echo "Removed!"\n}\n')
	write_file('${td}/usr/bin/scriptlet', '#!/bin/sh\necho "scriptlet package"\n')
	os.chmod('${td}/usr/bin/scriptlet', 0o755) or {}
	pack_pkg(td, 'scriptlet-1.0-1-x86_64')
	println('  wrote ${output_dir}/scriptlet-1.0-1-x86_64.pkg.tar.zst')
}

fn main() {
	ensure_output_dir()
	println('Generating package archive fixtures...')
	build_hello_pkg()
	build_libfoo_pkg()
	build_epoch_pkg()
	build_scriptlet_pkg()
	println('Done.')
}
